name: RFC propose

on:
  issue_comment:
    types: [created]

jobs:
  rfc-propose:
    name: Propose an RFC creation transaction
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/rfc-propose') }}
    runs-on: ubuntu-latest
    steps:
      - uses: paritytech/rfc-propose@main
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
